-- This file is automatically generated. DO NOT EDIT IT DIRECTLY!
-- Visit https://weblate.sir.insidi.at/or/projects/aetheriusbadgefilter/messages/de/ to update translations.
local settext = LibGetText("AetheriusBadgeFilter").settext
settext("Badge Filter", "Abzeichenfilter")
settext("Refresh Badges", "Abzeichen aktualisieren")
settext("Show Defined Badges", "Definierte Abzeichen anzeigen")
settext("Show Scanned Badges", "Gefundene Abzeichen anzeigen")
settext("Hide Member Count", "Mitgliederzahl verstecken")
settext("Lock Window", "Fenster sperren")
settext("Reset Window", "Fenster zurücksetzen")
settext("Showing Member Count", "Mitgliederzahl anzeigen")
settext("Unlock Window", "Fenster entsperren")
settext("Hide Window", "Fenster ausblenden")
settext("Toggle Aetherius Badge Filter Window", "Aetherius Badge Filter Fenster umschalten")
settext("Increment", "Erhöhen")
settext("No Badges found", "Keine Abzeichen gefunden")
settext("Decrement", "Vermindern")
settext("Update Color", "Farbe aktualisieren")
settext("Remove", "Entfernen")