-- This file is automatically generated. DO NOT EDIT IT DIRECTLY!
-- Visit https://weblate.sir.insidi.at/or/projects/aetheriusbadgefilter/messages/en/ to update translations.
local settext = LibGetText("AetheriusBadgeFilter").settext
settext("Badge Filter", "Badge Filter")
settext("Refresh Badges", "Refresh Badges")
settext("Show Defined Badges", "Show Defined Badges")
settext("Show Scanned Badges", "Show Scanned Badges")
settext("Hide Member Count", "Hide Member Count")
settext("Showing Member Count", "Showing Member Count")
settext("Unlock Window", "Unlock Window")
settext("Hide Window", "Hide Window")
settext("Toggle Aetherius Badge Filter Window", "Toggle Aetherius Badge Filter Window")
settext("No Badges found", "No Badges found")
settext("Lock Window", "Lock Window")
settext("Reset Window", "Reset Window")
settext("Increment", "Increment")
settext("Decrement", "Decrement")
settext("Update Color", "Update Color")
settext("Remove", "Remove")