-- This file is automatically generated. DO NOT EDIT IT DIRECTLY!
-- Visit https://weblate.sir.insidi.at/or/projects/aetheriusbadgefilter/messages/ru/ to update translations.
local settext = LibGetText("AetheriusBadgeFilter").settext
settext("Showing Member Count", "Показать Количество Награжденных")
settext("Update Color", "Выбрать Цвет")
settext("Lock Window", "Заблокировать")
settext("Reset Window", "Восстановить")
settext("Hide Window", "Скрыть")
settext("Toggle Aetherius Badge Filter Window", "Изменить Режим Aetherius Badge Filter")
settext("No Badges found", "Значков Не Найдено")
settext("Remove", "Удалить")
settext("Increment", "Добавить")
settext("Decrement", "Убавить")
settext("Badge Filter", "Фильтр Значков")
settext("Refresh Badges", "Обновить Значки")
settext("Show Defined Badges", "Показать Созданные Значки")
settext("Show Scanned Badges", "Показать Найденные Значки")
settext("Hide Member Count", "Скрыть Количество Награжденных")
settext("Unlock Window", "Разблокировать")